In [2]:
import numpy as np

w = np.array([
    [1, 2, -1],
    [1, 0, 1],
    [0, 1, 0]
])

w_det = np.linalg.det(w)
print(w_det)

-2.0


In [3]:
w_inv = np.linalg.inv(w)
print(w_inv)

[[ 0.5  0.5 -1. ]
 [-0.  -0.   1. ]
 [-0.5  0.5  1. ]]


In [4]:
m_idt = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

In [5]:
w_multi = np.dot(w_inv, m_idt)
print(w_multi)

[[ 0.5  0.5 -1. ]
 [ 0.   0.   1. ]
 [-0.5  0.5  1. ]]


In [6]:
print(np.linalg.det(m_idt))

1.0


In [7]:
v_b = np.array([
    [5],
    [-2],
    [0]
])

print(v_b)

[[ 5]
 [-2]
 [ 0]]


In [8]:
w_multi_b = np.dot(w, v_b)
print(w_multi_b)

[[ 1]
 [ 5]
 [-2]]


In [9]:
v_m = np.array([
    [3,1,-7]
])

v_n = np.array([
    [2],
    [2],
    [0]
])

v_mn = np.dot(v_m, v_n)
print(v_mn)

[[8]]


In [10]:
m_a = np.array([
    [5, 2, 3],
    [-1, -3, 2],
    [0, 1, -1]
])

m_b = np.array([
    [1, 0, -4],
    [2, 1, 0],
    [8, -1, 0]
])

multi_ab = np.dot(m_a, m_b)
print(multi_ab)

[[ 33  -1 -20]
 [  9  -5   4]
 [ -6   2   0]]


In [11]:
m_ab_inv = np.linalg.inv(multi_ab)
print(m_ab_inv)

[[-3.84923045e+13 -1.92461523e+14 -5.00399959e+14]
 [-1.15476914e+14 -5.77384568e+14 -1.50119988e+15]
 [-5.77384568e+13 -2.88692284e+14 -7.50599938e+14]]


In [12]:
print(np.linalg.det(m_ab_inv))

0.0
