In [1]:
import numpy as np

In [12]:
m_a = np.array([
    [2,1],
    [-3,6]
])

a_eigen_values, a_eigen_vector = np.linalg.eig(m_a)

print("Eigen values : ")
print(a_eigen_values)

print("Eigen vectors :")
print(a_eigen_vector)

Eigen values : 
[3. 5.]
Eigen vectors :
[[-0.70710678 -0.31622777]
 [-0.70710678 -0.9486833 ]]


In [16]:
m_id = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])

id_eigen_values, id_eigen_vector = np.linalg.eig(m_id)

print("Eigen values : ")
print(id_eigen_values)

print("Eigen vectors :")
print(id_eigen_vector)

Eigen values : 
[1. 1. 1.]
Eigen vectors :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
mat_a = np.array([
    [1,2],
    [0,4]
])

mat_b = np.array([
    [1,0],
    [0,1]
])

mat_ab = np.dot(mat_a, mat_b)
print(mat_ab)

[[1 2]
 [0 4]]


In [19]:
ab_eigen_values, ab_eigen_vector = np.linalg.eig(mat_ab)

print("Eigen values : ")
print(ab_eigen_values)

print("Eigen vectors :")
print(ab_eigen_vector)

Eigen values : 
[1. 4.]
Eigen vectors :
[[1.         0.5547002 ]
 [0.         0.83205029]]


In [21]:
m_p = np.array([
    [2,0,0],
    [1,2,1],
    [-1,0,1]
])

p_eigen_values, p_eigen_vector = np.linalg.eig(m_p)

print("Eigen values : ")
print(p_eigen_values)

print("Eigen vectors :")
print(p_eigen_vector)

Eigen values : 
[2. 1. 2.]
Eigen vectors :
[[ 0.          0.          0.70710678]
 [ 1.         -0.70710678  0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [22]:
m_c = np.array([
    [3,1,-2],
    [4,0,1],
    [2,1,-1]
])

c_eigen_values, c_eigen_vector = np.linalg.eig(m_c)

print("Eigen values : ")
print(c_eigen_values)

print("Eigen vectors :")
print(c_eigen_vector)

Eigen values : 
[ 2.79128785  1.         -1.79128785]
Eigen vectors :
[[-0.43816211  0.08543577  0.31958037]
 [-0.78487447  0.85435766 -0.89204079]
 [-0.43816211  0.51261459  0.31958037]]
