## System linear 3 variabel

In [1]:
import numpy as np

4a−3b+𝑥c=−10,
2a+b+3c=0,
−a+2b−5c=17

##### solving with system linear using matrices

In [2]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("\n",A)
print("\n",b)



 [[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

 [-10.   0.  17.]


In [3]:
x = np.linalg.solve(A, b)
print(x)

[ 1.  4. -2.]


a = 1, b = 4, c = -2

##### Evaluation determinant 

In [4]:
d = np.linalg.det(A)

print(f"{d:.2f}")

-60.00


In [5]:
A_sys = np.hstack((A, b.reshape((3, 1))))
print(A_sys)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


### Functions for elementary operations

- Multify any row by a non-zero number
- Add two rows and exchange one of the original rows with the result of addition
- Swap rows

In [6]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

In [7]:
print("Original matrix :")
print(A_sys)

print("\nMultiply third row  by 2 :")
print(MultiplyRow(A_sys, 2, 2))

print("\nExchange third row with the sum itself and second row multiplied by 1/2 :")
print("(Row 3) + 1/2 x (Row 2)")
print(AddRows(A_sys, 1, 2, 1/2))

print("\nExchange its first and third rows :")
print(SwapRows(A_sys, 0, 2))

Original matrix :
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Multiply third row  by 2 :
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]

Exchange third row with the sum itself and second row multiplied by 1/2 :
(Row 3) + 1/2 x (Row 2)
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]

Exchange its first and third rows :
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


If you input a singular matrix (redundant or contradictory), the code will show an error 'Singular Matrix.