In [64]:
import numpy as np
import cv2

##### Transformations

In [65]:
def T(v):
    w = np.zeros((3,1))
    w[0,0] = 3*v[0,0]
    w[2,0] = -2*v[1,0]
    
    return w

v = np.array([[3],[5]])
w = T(v)

print("Origin vector:\n", v, "\n\n Result of the transformation:\n", w)

Origin vector:
 [[3]
 [5]] 

 Result of the transformation:
 [[  9.]
 [  0.]
 [-10.]]


#### Linear Transformations

In [66]:
u = np.array([[1],[-2]])
v = np.array([[2],[4]])

k = 7

print("T(k*v):\n", T(k*v))
print("\nk*T(v):\n", k*T(v))
print("\nT(u+v):\n", T(u+v))
print("\nT(u)+T(v):\n", T(u)+T(v))

T(k*v):
 [[ 42.]
 [  0.]
 [-56.]]

k*T(v):
 [[ 42.]
 [  0.]
 [-56.]]

T(u+v):
 [[ 9.]
 [ 0.]
 [-4.]]

T(u)+T(v):
 [[ 9.]
 [ 0.]
 [-4.]]


##### Im just proving it

k * v = 7 * 2 | 7 * 4 \
      = 14 | 28 \
      v1 = 14 * 3 = 42 \
      v2 = 0 * 8 = 0 \
      v3 = 28 * -2 = -56 

k * T(v) = \
      T(v1) = 2 * 3 = 6 \
      T(v2) = 0 * 0 = 0 \
      T(v3) = 4 * -2 = -8 \
      k * T(v1) = 7 * 6 = 42 \
      k * T(v2) = 0 * 0 = 0 \
      k * T(v3) = 7 * -8 = -56 

#### Transformations Defined as a Matrix Multiplication

In [67]:
def L(v):
    A = np.array([[3,0], [0,0], [0,-2]])
    print("Transformation matrix : \n", A, "\n")
    w = A @ v

    return w

v = np.array([[3],[5]])
w = L(v)

print("Original vector : \n", v, "\n\n Result of the transformation : \n", w)

Transformation matrix : 
 [[ 3  0]
 [ 0  0]
 [ 0 -2]] 

Original vector : 
 [[3]
 [5]] 

 Result of the transformation : 
 [[  9]
 [  0]
 [-10]]


#### Standard Transformations in a Plane

Ex 1 (Horizontal Scaling)

In [70]:
def T_hscaling(v):
    A = np.array([[2,0],[0,1]])
    w = A @ v
    
    return w

def transform_vectors(T, v1, v2):
    V = np.hstack((v1, v2))
    W  = T(V)

    return W

e1 = np.array([[1],[0]])
e2 = np.array([[0],[1]])

transformation_result_hscaling = transform_vectors(T_hscaling, e1, e2)

print("Original vectors:\n e1= \n", e1, "\n e2=\n", e2, 
    "\n\n Result of the transformation (matrix form):\n", transformation_result_hscaling)

Original vectors:
 e1= 
 [[1]
 [0]] 
 e2=
 [[0]
 [1]] 

 Result of the transformation (matrix form):
 [[2 0]
 [0 1]]


Ex 2 (Reflection about y-axis (vertical axis))

In [71]:
def T_reflection_yaxis(v):
    A = np.array([[-1,0], [0,1]])
    w = A @ v
    
    return w
    
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

transformation_result_reflection_yaxis = transform_vectors(T_reflection_yaxis, e1, e2)

print("Original vectors:\n e1= \n", e1,"\n e2=\n", e2, 
    "\n\n Result of the transformation (matrix form):\n", transformation_result_reflection_yaxis)

Original vectors:
 e1= 
 [[1]
 [0]] 
 e2=
 [[0]
 [1]] 

 Result of the transformation (matrix form):
 [[-1  0]
 [ 0  1]]
