In [1]:
import numpy as np

#### Matrix Multipication using Python

In [4]:
A = np.array([
    [4, 9, 9],
    [9, 1, 6],
    [9, 2, 3],
])

B = np.array([
    [2, 2],
    [5, 7],
    [4, 4]
])

In [5]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [6]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

#### Matrix Convention and Broadcasting

In [7]:
try:
    np.matmul(B, A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [9]:
try:
    B @ A
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [13]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])


In [16]:
print(x,y)

[ 1 -2 -5] [ 4  3 -1]


In [14]:
print("Shape of vector x : ", x.shape)
print("Number of dimension of vector x : ", x.ndim)
print("Shape of vector x, reshaped to a matrix : ", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshape to matrix : ", x.reshape((3, 1)).ndim)

Shape of vector x :  (3,)
Number of dimension of vector x :  1
Shape of vector x, reshaped to a matrix :  (3, 1)
Number of dimensions of vector x, reshape to matrix :  2


In [22]:
x_reshape_check = x.reshape(3,1)
print(x, x.shape)
print(x_reshape_check, x_reshape_check.shape)

[ 1 -2 -5] (3,)
[[ 1]
 [-2]
 [-5]] (3, 1)


In [23]:
np.matmul(x, y)

3

In [24]:
try:
    np.matmul(x.reshape((3, 1)), y.reshape((3, 1)))
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


In [25]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [26]:
A - 2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])